[package]
name = "buscador-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
slint = "1.0"
tempfile = "3.20.0"

[build-dependencies]
slint-build = "1.0"

